// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimeTracker.Infrastructure.Persistence;

#nullable disable

namespace TimeTracker.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TimeTrackerDbContext))]
    [Migration("20260605164847_AddUserDarkModeCompact")]
    partial class AddUserDarkModeCompact
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TimeTracker.Domain.Entities.CalendarConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountEmail")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)")
                        .HasColumnName("account_email");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_utc");

                    b.Property<DateTime?>("LastSyncUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_sync_utc");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("modified_utc");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("provider");

                    b.Property<string>("RefreshTokenProtected")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("refresh_token_protected");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("scopes");

                    b.Property<string>("TenantId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tenant_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Provider")
                        .IsUnique();

                    b.ToTable("t_calendar_connection", (string)null);
                });

            modelBuilder.Entity("TimeTracker.Domain.Entities.CalendarSeriesTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_utc");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("modified_utc");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<string>("SeriesUid")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("series_uid");

                    b.Property<int?>("TaskId")
                        .HasColumnType("int")
                        .HasColumnName("task_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId");

                    b.HasIndex("OrganizationId", "UserId", "SeriesUid")
                        .IsUnique();

                    b.ToTable("t_calendar_series_tag", (string)null);
                });

            modelBuilder.Entity("TimeTracker.Domain.Entities.CalendarSeriesTagAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CalendarSeriesTagId")
                        .HasColumnType("int")
                        .HasColumnName("calendar_series_tag_id");

                    b.Property<int>("TimeEntryFieldId")
                        .HasColumnType("int")
                        .HasColumnName("time_entry_field_id");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("TimeEntryFieldId");

                    b.HasIndex("CalendarSeriesTagId", "TimeEntryFieldId")
                        .IsUnique();

                    b.ToTable("t_calendar_series_tag_attribute", (string)null);
                });

            modelBuilder.Entity("TimeTracker.Domain.Entities.FieldDataTypeLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("t_type_field_data_type", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "text",
                            Name = "Text"
                        },
                        new
                        {
                            Id = 2,
                            Code = "number",
                            Name = "Number"
                        },
                        new
                        {
                            Id = 3,
                            Code = "date",
                            Name = "Date"
                        },
                        new
                        {
                            Id = 4,
                            Code = "boolean",
                            Name = "Boolean"
                        },
                        new
                        {
                            Id = 5,
                            Code = "select",
                            Name = "Select"
                        });
                });

            modelBuilder.Entity("TimeTracker.Domain.Entities.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("modified_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<bool>("RequireTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("require_time");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("t_organization", (string)null);
                });

            modelBuilder.Entity("TimeTracker.Domain.Entities.OrganizationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_utc");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("modified_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique();

                    b.ToTable("t_organization_role", (string)null);
                });

            modelBuilder.Entity("TimeTracker.Domain.Entities.OrganizationRoleRight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrganizationRoleId")
                        .HasColumnType("int")
                        .HasColumnName("organization_role_id");

                    b.Property<int>("Right")
                        .HasColumnType("int")
                        .HasColumnName("right");

                    b.HasKey("Id");

                    b.HasIndex("Right");

                    b.HasIndex("OrganizationRoleId", "Right")
                        .IsUnique();

                    b.ToTable("t_organization_role_right", (string)null);
                });

            modelBuilder.Entity("TimeTracker.Domain.Entities.RightLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("t_type_right", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "manage_organization",
                            Description = "Edit organization details.",
                            Name = "Manage organization"
                        },
                        new
                        {
                            Id = 2,
                            Code = "manage_users",
                            Description = "Invite members and assign their roles.",
                            Name = "Manage users"
                        },
                        new
                        {
                            Id = 3,
                            Code = "manage_roles",
                            Description = "Create and edit roles and their rights.",
                            Name = "Manage roles"
                        },
                        new
                        {
                            Id = 4,
                            Code = "manage_fields",
                            Description = "Configure the time-entry fields.",
                            Name = "Manage fields"
                        },
                        new
                        {
                            Id = 5,
                            Code = "view_reports",
                            Description = "View time reports and summaries.",
                            Name = "View reports"
                        });
                });

            modelBuilder.Entity("TimeTracker.Domain.Entities.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_utc");

                    b.Property<DateTime?>("DeletedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<decimal?>("EstimatedHours")
                        .HasColumnType("decimal(7,2)")
                        .HasColumnName("estimated_hours");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit")
                        .HasColumnName("is_complete");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("modified_utc");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<int?>("PercentBeforeComplete")
                        .HasColumnType("int")
                        .HasColumnName("percent_before_complete");

                    b.Property<int>("PercentComplete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("percent_complete");

                    b.Property<int?>("Priority")
                        .HasColumnType("int")
                        .HasColumnName("priority");

                    b.Property<string>("Project")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("project");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("title");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("UserId", "IsComplete");

                    b.ToTable("t_task", (string)null);
                });

            modelBuilder.Entity("TimeTracker.Domain.Entities.TimeEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_utc");

                    b.Property<DateTime?>("DeletedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_utc");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int")
                        .HasColumnName("duration_minutes");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date")
                        .HasColumnName("entry_date");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("modified_utc");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<int>("Source")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("source");

                    b.Property<string>("SourceEventId")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("source_event_id");

                    b.Property<bool>("SourceIsRecurring")
                        .HasColumnType("bit")
                        .HasColumnName("source_is_recurring");

                    b.Property<DateTime?>("SourceOccurrenceStartUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("source_occurrence_start_utc");

                    b.Property<string>("SourceSeriesUid")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("source_series_uid");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("start_time");

                    b.Property<int?>("TaskId")
                        .HasColumnType("int")
                        .HasColumnName("task_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.HasIndex("OrganizationId", "EntryDate");

                    b.HasIndex("UserId", "EntryDate");

                    b.HasIndex("OrganizationId", "UserId", "SourceSeriesUid", "SourceOccurrenceStartUtc")
                        .IsUnique()
                        .HasFilter("[source_series_uid] IS NOT NULL AND [deleted_utc] IS NULL");

                    b.ToTable("t_time_entry", (string)null);
                });

            modelBuilder.Entity("TimeTracker.Domain.Entities.TimeEntryAttribute", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("TimeEntryFieldId")
                        .HasColumnType("int")
                        .HasColumnName("time_entry_field_id");

                    b.Property<long>("TimeEntryId")
                        .HasColumnType("bigint")
                        .HasColumnName("time_entry_id");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("TimeEntryFieldId");

                    b.HasIndex("TimeEntryId", "TimeEntryFieldId")
                        .IsUnique();

                    b.ToTable("t_time_entry_attribute", (string)null);
                });

            modelBuilder.Entity("TimeTracker.Domain.Entities.TimeEntryField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_utc");

                    b.Property<int>("DataType")
                        .HasColumnType("int")
                        .HasColumnName("data_type");

                    b.Property<string>("FieldKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("field_key");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit")
                        .HasColumnName("is_required");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("label");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("modified_utc");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<int?>("OrganizationRoleId")
                        .HasColumnType("int")
                        .HasColumnName("organization_role_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("DataType");

                    b.HasIndex("OrganizationRoleId");

                    b.HasIndex("OrganizationId", "FieldKey")
                        .IsUnique();

                    b.ToTable("t_time_entry_field", (string)null);
                });

            modelBuilder.Entity("TimeTracker.Domain.Entities.TimeEntryFieldOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("icon");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("label");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<int>("TimeEntryFieldId")
                        .HasColumnType("int")
                        .HasColumnName("time_entry_field_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("TimeEntryFieldId", "SortOrder");

                    b.ToTable("t_time_entry_field_option", (string)null);
                });

            modelBuilder.Entity("TimeTracker.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CompactMode")
                        .HasColumnType("bit")
                        .HasColumnName("compact_mode");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_utc");

                    b.Property<bool>("DarkMode")
                        .HasColumnType("bit")
                        .HasColumnName("dark_mode");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)")
                        .HasColumnName("email");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("external_id");

                    b.Property<bool>("HideOrgSwitcher")
                        .HasColumnType("bit")
                        .HasColumnName("hide_org_switcher");

                    b.Property<bool>("IsGlobalAdmin")
                        .HasColumnType("bit")
                        .HasColumnName("is_global_admin");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("modified_utc");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasFilter("[external_id] IS NOT NULL");

                    b.ToTable("t_user", (string)null);
                });

            modelBuilder.Entity("TimeTracker.Domain.Entities.UserOrganization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_utc");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit")
                        .HasColumnName("is_default");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("modified_utc");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("UserId", "OrganizationId")
                        .IsUnique();

                    b.ToTable("t_user_organization", (string)null);
                });

            modelBuilder.Entity("TimeTracker.Domain.Entities.UserOrganizationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrganizationRoleId")
                        .HasColumnType("int")
                        .HasColumnName("organization_role_id");

                    b.Property<int>("UserOrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("user_organization_id");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationRoleId");

                    b.HasIndex("UserOrganizationId", "OrganizationRoleId")
                        .IsUnique();

                    b.ToTable("t_user_organization_role", (string)null);
                });

            modelBuilder.Entity("TimeTracker.Domain.Entities.CalendarConnection", b =>
                {
                    b.HasOne("TimeTracker.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TimeTracker.Domain.Entities.CalendarSeriesTag", b =>
                {
                    b.HasOne("TimeTracker.Domain.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TimeTracker.Domain.Entities.TaskItem", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TimeTracker.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TimeTracker.Domain.Entities.CalendarSeriesTagAttribute", b =>
                {
                    b.HasOne("TimeTracker.Domain.Entities.CalendarSeriesTag", "CalendarSeriesTag")
                        .WithMany("Attributes")
                        .HasForeignKey("CalendarSeriesTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TimeTracker.Domain.Entities.TimeEntryField", "TimeEntryField")
                        .WithMany()
                        .HasForeignKey("TimeEntryFieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CalendarSeriesTag");

                    b.Navigation("TimeEntryField");
                });

            modelBuilder.Entity("TimeTracker.Domain.Entities.OrganizationRole", b =>
                {
                    b.HasOne("TimeTracker.Domain.Entities.Organization", "Organization")
                        .WithMany("Roles")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("TimeTracker.Domain.Entities.OrganizationRoleRight", b =>
                {
                    b.HasOne("TimeTracker.Domain.Entities.OrganizationRole", "OrganizationRole")
                        .WithMany("Rights")
                        .HasForeignKey("OrganizationRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TimeTracker.Domain.Entities.RightLookup", "RightLookup")
                        .WithMany()
                        .HasForeignKey("Right")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrganizationRole");

                    b.Navigation("RightLookup");
                });

            modelBuilder.Entity("TimeTracker.Domain.Entities.TaskItem", b =>
                {
                    b.HasOne("TimeTracker.Domain.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TimeTracker.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TimeTracker.Domain.Entities.TimeEntry", b =>
                {
                    b.HasOne("TimeTracker.Domain.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TimeTracker.Domain.Entities.TaskItem", "Task")
                        .WithMany("TimeEntries")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TimeTracker.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TimeTracker.Domain.Entities.TimeEntryAttribute", b =>
                {
                    b.HasOne("TimeTracker.Domain.Entities.TimeEntryField", "TimeEntryField")
                        .WithMany()
                        .HasForeignKey("TimeEntryFieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TimeTracker.Domain.Entities.TimeEntry", "TimeEntry")
                        .WithMany("Attributes")
                        .HasForeignKey("TimeEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TimeEntry");

                    b.Navigation("TimeEntryField");
                });

            modelBuilder.Entity("TimeTracker.Domain.Entities.TimeEntryField", b =>
                {
                    b.HasOne("TimeTracker.Domain.Entities.FieldDataTypeLookup", "DataTypeLookup")
                        .WithMany()
                        .HasForeignKey("DataType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TimeTracker.Domain.Entities.Organization", "Organization")
                        .WithMany("TimeEntryFields")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TimeTracker.Domain.Entities.OrganizationRole", "OrganizationRole")
                        .WithMany()
                        .HasForeignKey("OrganizationRoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DataTypeLookup");

                    b.Navigation("Organization");

                    b.Navigation("OrganizationRole");
                });

            modelBuilder.Entity("TimeTracker.Domain.Entities.TimeEntryFieldOption", b =>
                {
                    b.HasOne("TimeTracker.Domain.Entities.TimeEntryField", "TimeEntryField")
                        .WithMany("Options")
                        .HasForeignKey("TimeEntryFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TimeEntryField");
                });

            modelBuilder.Entity("TimeTracker.Domain.Entities.UserOrganization", b =>
                {
                    b.HasOne("TimeTracker.Domain.Entities.Organization", "Organization")
                        .WithMany("Members")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TimeTracker.Domain.Entities.User", "User")
                        .WithMany("Organizations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TimeTracker.Domain.Entities.UserOrganizationRole", b =>
                {
                    b.HasOne("TimeTracker.Domain.Entities.OrganizationRole", "OrganizationRole")
                        .WithMany("Members")
                        .HasForeignKey("OrganizationRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TimeTracker.Domain.Entities.UserOrganization", "UserOrganization")
                        .WithMany("Roles")
                        .HasForeignKey("UserOrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrganizationRole");

                    b.Navigation("UserOrganization");
                });

            modelBuilder.Entity("TimeTracker.Domain.Entities.CalendarSeriesTag", b =>
                {
                    b.Navigation("Attributes");
                });

            modelBuilder.Entity("TimeTracker.Domain.Entities.Organization", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Roles");

                    b.Navigation("TimeEntryFields");
                });

            modelBuilder.Entity("TimeTracker.Domain.Entities.OrganizationRole", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Rights");
                });

            modelBuilder.Entity("TimeTracker.Domain.Entities.TaskItem", b =>
                {
                    b.Navigation("TimeEntries");
                });

            modelBuilder.Entity("TimeTracker.Domain.Entities.TimeEntry", b =>
                {
                    b.Navigation("Attributes");
                });

            modelBuilder.Entity("TimeTracker.Domain.Entities.TimeEntryField", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("TimeTracker.Domain.Entities.User", b =>
                {
                    b.Navigation("Organizations");
                });

            modelBuilder.Entity("TimeTracker.Domain.Entities.UserOrganization", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
